spring.application.name=Desafio-grupo-ras
app.profile.name=default

# DATASOURCE

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# FLYWAY

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration



